### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by kidandcat** [8byt/gox#4]
The first README example doesn't works:

```
package main

import "github.com/gopherjs/vecty"

func main() {
	woah := <body>
		<div class="amazing">
			<h1>gox</h1>
			<span class={"you could put dynamic content here"}/>
			yeah you can do bare words too
		</div>
	</body>
	
	vecty.RenderBody(woah)
}
```

main.go:9:19: cannot use woah (variable of type *vecty.HTML) as vecty.Component value in argument to vecty.RenderBody: missing method Context

**Comment by HALtheWise** [comment]
It looks like this is due to a breaking change in Vecty, but I haven't pinpointed which one yet. https://github.com/gopherjs/vecty/blob/master/doc/CHANGELOG.md

**Comment by HALtheWise** [comment]
Should be resolved now.
